project:
  type: website
  output-dir: docs

website:
  title: "SciK-Health"
  navbar:
    left:
      - text: The Project
        href: theProject.qmd
      - text: Research Team
        href: team.qmd
      - text: Research Metrics
        menu:
        - text: Sources
          href: sources.qmd
        - text: Performance Indicators
          href: performance.qmd
      - text: Data repository
        menu:
        - text: Data Description
          href: description.qmd
        - text: AHC data
          href: data.qmd
      - text: References & Products
        menu:
        - text: Project References
          href: references.qmd
        - text: Publications
          href: publications.qmd
        - text: Conferences
          href: conferences.qmd
        - text: Workshops
          href: workshops.qmd
format:
  html:
    include-in-header: _includes/banner.html
    theme: lux
    css: styles.css
    toc: true
    page-layout: full

editor: visual

